spring.application.name=ReactiveProg1

# ==================================================
# = H2 Reactive Database Configuration (R2DBC)
# ==================================================

# Keep DB alive while Spring is running
#spring.r2dbc.url=r2dbc:h2:file:///C:/data/h2/testdb222;DB_CLOSE_DELAY=-1
spring.r2dbc.url=r2dbc:h2:mem:///testdb222;DB_CLOSE_DELAY=-1

# Username and password (optional for in-memory H2)
spring.r2dbc.username=sa
spring.r2dbc.password=

## JDBC connection for H2 console only
#spring.datasource.url=jdbc:h2:mem:testdb222;DB_CLOSE_DELAY=-1
#spring.datasource.username=sa
#spring.datasource.password=


# Show SQL in logs
spring.r2dbc.properties.logging.level=DEBUG

# Enable H2 console (only works with JDBC, not R2DBC)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==================================================
# = Spring Data R2DBC Settings
# ==================================================
spring.sql.init.mode=always
spring.sql.init.platform=h2

# Location for schema and data files (optional)
spring.sql.init.schema-locations=classpath:schema.sql


# ==================================================
# = Logging
# ==================================================
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.h2=DEBUG
